import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "components/Navbar";
import Menubar from "components/Menubar";
import FooterBar from "components/FooterBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Animanga List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col items-center bg-main-dark`}
      >
        <div className="container">
          <Navbar />
          <Menubar />
          {children}
          <FooterBar />
        </div>
      </body>
    </html>
  );
}
